import { Lato } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import './global.css'
import { Providers } from './providers'

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
}

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap',
})

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang='en'
      className={`${lato.className}`}
      suppressHydrationWarning={true}
    >
      <body className={'overflow-hidden'}>
        <Providers>
          <NextTopLoader showSpinner={false} />
          {children}
        </Providers>
      </body>
    </html>
  )
}
